openapi: 3.0.3
info:
    title: 'The Censorship API API'
    description: 'The Censorship API gives you the power to censor anybody, anywhere. Keep them from using dirty words, like "family", and "love". Ugh🤮.'
    version: 1.0.0
servers:
    -
        url: 'http://localhost:8000'
paths:
    /api/healthcheck:
        get:
            summary: 'Health check'
            description: "Check if the API is still alive.\n\nPS. This is a Closure route. 😄"
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: ''
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: 'Hi!! 👋'
            tags:
                - Endpoints
            security: []
components:
    securitySchemes:
        default:
            type: http
            scheme: bearer
            description: ''
security:
    -
        default: []
